server:
  port: 8122
unsplash:
  authorize:
    codeUrl: https://unsplash.com/oauth/authorize
    tokenUrl: https://unsplash.com/oauth/token
    client_id: ejcxMYgmWK3jRhq90P3UkVUDWWtsJ50DRCSqn4b_p10
    redirect_uri: urn:ietf:wg:oauth:2.0:oob
    response_type: code
    scope: public
    client_secret: swFAGG13O7nja0ZHvBVhw_N4gjx9gVLbf7YjTtxdf_g
    grant_type: authorization_code
    token: Bearer xIRKRbXr1hnvZnTUBxar3vzjjnTFfRm8m09Krt2C3SE
    collectionUrl: https://api.unsplash.com/collections
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/unsplashtest?serverTimezone=UTC
    username: root
    password: root
  application:
    name: unsplash-test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect



